---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/docs"
site_name: "Nautobot Firewall Models Documentation"
site_url: "https://nautobot-plugin-firewall-models.readthedocs.io/"
site_dir: nautobot_firewall_models/static/nautobot_firewall_models/docs
repo_url: "https://github.com/nautobot/nautobot-plugin-firewall-models"
theme:
  name: "readthedocs"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
extra_css:
  - "extra.css"
markdown_extensions:
  - "admonition"
  - toc:
      permalink: true
plugins:
  - include-markdown
nav:
  - Introduction: "index.md"
  - Usage: "usage.md"
  - Examples: "example.md"
  - Development Environment: "development.md"
  - Models: "models.md"
  - Capirca Usage: "capirca.md"
