---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/nautobot-plugin-firewall-model/docs"
site_name: "NautobotFirewallModels Documentation"
site_url: "https://nautobot-plugin-firewall-model.readthedocs.io/"
site_dir: nautobot_firewall_models/static/nautobot_firewall_models/docs
repo_url: "https://github.com/networktocode-llc/nautobot-plugin-firewall-model"
theme:
  name: "readthedocs"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
extra_css:
  - "extra.css"
markdown_extensions:
  - "admonition"
  - toc:
      permalink: true
plugins:
    - include-markdown
nav:
  - Introduction: "index.md"
  - Models: "models.md"
